---
- name: set root password and shell
  user:
    name: root
    shell: /bin/bash
    password: "{{ root.password | password_hash('sha512', root.salt) }}"
  become: true
  
- name: set root bash prompt and ls aliases
  blockinfile:
    path: /root/.bashrc
    create: yes
    owner: root
    group: root
    mode: '0600'
    block: |
      export PS1='{{ prompt.root }}'
      
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'
  become: true
  
- name: set root vimrc config
  blockinfile:
    path: /root/.vimrc
    create: yes
    owner: root
    group: root
    mode: '0600'
    block: |
      set mouse-=a
  become: true
  
- name: set work_users password and shell
  user:
    name: "{{ item.name }}"
    shell: /bin/bash
    password: "{{ item.password | password_hash('sha512', item.salt) }}"
    groups: sudo
    append: yes
  with_items: "{{ work_users }}"
  become: true
  
- name: set work_users bash prompt and ls aliases
  blockinfile:
    path: "/home/{{ item.name }}/.bashrc"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
    block: |
      export PS1='{{ prompt.user }}'
      
      alias ls='ls $LS_OPTIONS'
      alias ll='ls $LS_OPTIONS -l'
      alias l='ls $LS_OPTIONS -lA'
  with_items: "{{ work_users }}"
  become: true
  
- name: set work_users vimrc config
  blockinfile:
    path: "/home/{{ item.name }}/.vimrc"
    create: yes
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: '0600'
    block: |
      set mouse-=a
  with_items: "{{ work_users }}"
  become: true
  