---
domain_name: "yggdrasil.local"
gateway: "192.168.1.1"
domain_name_servers: "192.168.1.254"
fqdn: "{{ hostname }}.{{ domain_name }}"

timezone: "Europe/Paris"

firmware:
  archive: 'vl805_update_0137ab.zip'
  new_bin:  'vl805_fw_0137ab.bin'
  old_bin:  'vl805_fw_013701.bin'

useful_tools:
- vim
- htop
- tree
- dnsutils

work_users:
- fanarie
# password should be define in a vault be overidden by vault content

prompt:
  user: '\[\033[38;5;22m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;3m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  root: '\[\033[38;5;1m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;27m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  
