---
domain_name: "yggdrasil.local"
fqdn: "{{ hostname }}.{{ domain_name }}"

certificate_authority:
  CN: 'Yggdrasil Certificate Authority'
  ST: 'MIDGARD'
  O:  'YGGDRASIL'
  OU: 'YGGDRASIL.LOCAL'

gateway: "192.168.1.1"
domain_name_servers: "192.168.1.254"

timezone: "Europe/Paris"

firmware:
  archive: 'vl805_update_0137ab.zip'
  new_bin:  'vl805_fw_0137ab.bin'
  old_bin:  'vl805_fw_013701.bin'

useful_tools:
- vim
- htop
- tree
- dnsutils

work_users:
- frederic
# password should be define in a vault or a plein text file as follow
#####################################
# ---
# passwords:
# - frederic: 'my_password'
#
# root_password: 'my_root_password'
#
# password_salt: 'my_password_salt'
#####################################
## You can generate a salt with the following command:
# cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1

prompts:
  user: '\[\033[38;5;22m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;3m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  root: '\[\033[38;5;1m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;27m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  
k8s:
  network_plugin: "weave"
  