---
domain_name: "yggdrasil.local"
fqdn: "{{ hostname }}.{{ domain_name }}"

certificate_authority:
  CN: 'Yggdrasil Certificate Authority'
  ST: 'MIDGARD'
  O:  'YGGDRASIL'
  OU: 'YGGDRASIL.LOCAL'

k8s_dashboard_url: k8s-dashboard.{{ domain_name }}
k8s_registry_url:  k8s-registry.{{ domain_name }}

ingress_certificate:
  CN: 'k8s-cluster.{{ domain_name }}'
  ST: '{{ certificate_authority.ST }}'
  O:  '{{ certificate_authority.O }}'
  OU: '{{ certificate_authority.OU }}'
  SAN:
  - "IP:{{ ansible_eth0.ipv4.address }}"
  - "DNS:{{ fqdn }}"
  - "DNS:{{ k8s_dashboard_url }}"
  - "DNS:{{ k8s_registry_url  }}"

gateway: "192.168.1.1"
domain_name_servers:
- "192.168.1.254"

timezone: "Europe/Paris"

firmware:
  archive: 'vl805_update_0137ab.zip'
  new_bin:  'vl805_fw_0137ab.bin'
  old_bin:  'vl805_fw_013701.bin'

useful_tools:
- vim
- htop
- tree
- dnsutils
- dos2unix
- unzip

# users and passwords should be defined in a vault or a plain text file or just here as follow:
#####################################
# work_users:
# - name: 'frederic'
#   password: 'my_password'
#
# root_password: 'my_root_password'
#
# password_salt: 'my_password_salt'
#####################################
# You can generate a salt with the following shell command:
# cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w ${1:-32} | head -n 1

prompts:
  user: '\[\033[38;5;22m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;3m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  root: '\[\033[38;5;1m\]\u@\h:\[$(tput sgr0)\]\[\033[38;5;27m\]\w\[$(tput sgr0)\]\[\033[38;5;15m\]\n\\$ \[$(tput sgr0)\]'
  
k8s:
  network_plugin:   "calico"
  flannel:
    cidr:           "10.244.0.0/16"
  calico:
    cidr:           "10.0.0.0/16"
  
ceph:
  net_mask:         "192.168.1.0/24"
  cluster_name:     "ceph"
  osd_drive:        "/dev/sda"
  # Less     than   5 OSDs set pg_num to  128
  # Between  5 and 10 OSDs set pg_num to  512
  # Between 10 and 50 OSDs set pg_num to 4096
  osd_pool:
    default_pg_num:   128
    default_pgp_num:  128
    default_size:     2
    default_min_size: 1
  rbd_pool:
    name: kube
    user: kube
#   pg_num:  128
#   pgp_num: 128
  
