---
domain_name: "yggdrasil.local"
gateway: "192.168.1.1"
domain_name_servers: "192.168.1.254"
fqdn: "{{ hostname }}.{{ domain_name }}"

work_users:
- name: "fanarie"
  password: "mypassword"

root_password: "mypassword"
