---
domain_name: "yggdrasil.local"
gateway: "192.168.1.1"
domain_name_servers: "192.168.1.254"
fqdn: "{{ hostname }}.{{ domain_name }}"

timezone: "Europe/Paris"

firmware_update:
  archive: 'vl805_update_0137ab.zip'
  binary:  'vl805_fw_0137ab.bin'

useful_tools:
- vim
- htop
- tree
- dnsutils

work_users:
- name: "fanarie"
  password: "mypassword"

root_password: "mypassword"
