---
apiVersion:         v1
kind:               Namespace
metadata:
  name:             docker-registry
---
kind:               PersistentVolumeClaim
apiVersion:         v1
metadata:
  name:             docker-registry-rdb-claim
  namespace:        docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: csi-rbd-sc
  resources:
    requests:
      storage:      10Gi
---
apiVersion:         apps/v1
kind:               Deployment
metadata:
  name:             docker-registry
  namespace:        docker-registry
spec:
  selector:
    matchLabels:
      app:          docker-registry
  replicas:         1
  strategy:
    type:           Recreate
  template:
    metadata:
      labels:
        app:        docker-registry
    spec:
      containers:
      - name:       docker-registry
        image:      registry:2
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path:       /v2/
            port:       5000
          initialDelaySeconds: 3
          periodSeconds:        3
        volumeMounts:
        - mountPath:    /var/lib/registry
          name:         docker-registry-data
      volumes:
      - name:           docker-registry-data
        persistentVolumeClaim:
          claimName:    docker-registry-rdb-claim
---
apiVersion:         v1
kind:               Service
metadata:
  name:             docker-registry-service
  namespace:        docker-registry
spec:
  ports:
  - name:           http
    targetPort:     5000
    port:           5000
  selector:
    app:            docker-registry
---
apiVersion:         extensions/v1beta1
kind:               Ingress
metadata:
  name:             registry-ingress
  namespace:        docker-registry
  annotations:
    kubernetes.io/ingress.class:                    nginx
    ingress.kubernetes.io/ssl-passthrough:          "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size:    "0" 
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600" 
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600" 
spec:
  tls:
  - hosts:
    - k8s-registry.yggdrasil.local
    secretName:     tlssecret
  rules:
  - http:
      paths:
        - path: /
          backend:
            serviceName: docker-registry-service
            servicePort: 5000
---