---
- name: Update and upgrade apt packages
  apt:
    upgrade:            dist
    update_cache:       yes
    force_apt_get:      yes
  become:               true
  
- name: install ceph osd packages and their dependencies
  apt: 
    name:               "{{ packages }}"
    state:              present
    autoremove:         yes
    force_apt_get:      yes
    install_recommends: no
  vars:
    packages:
    - "acl"             # needed for ansible become_user
    - "ceph-osd"
  become:               true
  
- name: assigne the correct user recursively to ceph folders
  file:
    path:               "{{ item }}"
    state:              directory
    owner:              ceph
    group:              ceph
    recurse:            yes
  with_items:
  - "/var/lib/ceph"
  - "/etc/ceph"
  become:               true
  
- name: copy ceph conf file on host
  copy:
    src:                "files/generated/ceph.conf"
    dest:               "/etc/ceph/ceph.conf"
    owner:              ceph
    group:              ceph
    mode:               '0644'
  become:               true
  
- name: copy ceph admin keyring file on host
  copy:
    src:                "files/generated/ceph.client.admin.keyring"
    dest:               "/etc/ceph/ceph.client.admin.keyring"
    owner:              ceph
    group:              ceph
    mode:               '0600'
  become:               true
  
- name: copy ceph bootstrap-osd keyring file on host
  copy:
    src:                "files/generated/ceph.bootstrap-osd.keyring"
    dest:               "/var/lib/ceph/bootstrap-osd/ceph.keyring"
    owner:              ceph
    group:              ceph
    mode:               '0600'
  become:               true
  
# create {{ ceph.osd_drive }}1 logical volume
- name: create osd logical volume and volume group
  block:
  - name: wipe drive
    shell:              "wipefs --all --force  {{ ceph.osd_drive }}"
    
  - name: make sure that first octets are clean
    shell:              "dd if=/dev/zero    of={{ ceph.osd_drive }} bs=1M bs=446 count=1"
    
  - name: create primary partition
    shell:              "echo '2048,,,' | sfdisk {{ ceph.osd_drive }}"
    
  become: true
  
- name: set_fact uniq ceph vg name
  set_fact:
    ceph_vgname:        "ceph-{{ 9999999999999999999999 | random | to_uuid }}"
    
- name: Create a ceph unique volume group (bug in ceph-volume, when it not exists)
  lvg:
    vg:                 "{{ ceph_vgname }}"
    pvs:                "{{ ceph.osd_drive }}1"
  become: true
  
- name: create ceph volume
  shell:                "ceph-volume lvm prepare --data {{ ceph.osd_drive }}1"
  become:               true
  
- name: execute ceph volume data command
  shell:                "ceph-volume lvm list --format json"
  register:             ceph_volumes_command
  changed_when:         false
  become:               true
  
- name: set_fact ceph_volumes
  set_fact:
    ceph_volumes:       "{{ (ceph_volumes_command.stdout | from_json).values() | flatten | map(attribute='tags') | flatten | list }}"
  
- name: activate ceph volume
  shell:                "ceph-volume lvm activate {{ item['ceph.osd_id'] }} {{ item['ceph.osd_fsid'] }}"
  with_items:           "{{ ceph_volumes }}"
  become:               true
  
- name: restart and enable ceph osd service
  systemd:
    name:               "ceph-osd@{{ item['ceph.osd_id'] }}"
    state:              restarted
    daemon_reload:      yes
    enabled:            true
  with_items:           "{{ ceph_volumes }}"
  become:               true
  