---
- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove:   yes
  become: true
 
- name: add useful tooling
  apt:
    name: "{{ item }}"
  with_items: "{{ useful_tools }}"
  become: true
  
- name: unarchive firmware files
  unarchive:
    src: "{{ firmware.archive }}"
    dest: /tmp
    mode: '0500'
    extra_opts:
    - vl805
    - "{{ firmware.binary }}"
  changed_when: false
  become: true

- name: Check firmware version
  shell: /tmp/vl805 -c /tmp/vl805_fw_0137ab.bin
  register: firmware_check
  changed_when: false
  become: true
  
- name: Update firmware if needed
  shell: /tmp/vl805 -w /tmp/vl805_fw_0137ab.bin
  when: firmware_check.rc != 0
  become: true

- name: remove firmware files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
  - vl805
  - "{{ firmware.binary }}"
  changed_when: false
  become: true

#timedatectl set-timezone 'Europe/Paris'
