---
- name: Install ceph binaries
  apt: 
    name:           "{{ packages }}"
    state:          present
    update_cache:   yes
    autoremove:     yes
    force_apt_get:  yes
  vars:
    packages:
    - "ceph-base"
    - "ceph-common"
  become:           true
  
- name: create /etc/ceph folders
  file:
    path:           "/etc/ceph"
    owner:          ceph
    group:          ceph
    mode:           '0755'
    state:          directory
  become:           true
  
- name: create /etc/ceph folders
  file:
    path:           "/var/run/ceph"
    owner:          ceph
    group:          ceph
    mode:           '0770'
    state:          directory
  become:           true
  