---
- name: Copy label node command to local file
  shell:        "kubectl label node {{ item }} node-role.kubernetes.io/worker=worker --overwrite"
  with_items:   "{{ hostvars['worker'] | map(attribute='hostname') | list }}"
  become:       true
  