---
- name: set worker nodes' label to worker
  shell:        "kubectl label node {{ hostvars[item].hostname }} node-role.kubernetes.io/worker=worker --overwrite"
  with_items:   "{{ groups['worker'] }}"
  become:       true
  