---
- name: kubernetes with calico  network plugin config
  block:
  - name: ensure /etc/NetworkManager/conf.d exists
    file:
      dest:             "/etc/NetworkManager/conf.d"
      state:            directory
      owner:            root
      group:            root
      mode:             '0755'
    
  - name: Create networking exception for calico
    copy:
      dest:             "/etc/NetworkManager/conf.d/calico.conf"
      content:          |
        [keyfile]
        unmanaged-devices=interface-name:cali*;interface-name:tunl*
      owner:            root
      group:            root
      mode:             '0644'
    register:           networking_exception_for_calico
    
  - name: restart service networkd
    systemd:
      name:             systemd-networkd
      state:            restarted
    when:               networking_exception_for_calico is changed
  
  become:               true
  when:                 k8s.network_plugin == 'calico'
  
- name: execute join command
  block:
  - name: create temporary folder
    tempfile:
      state:        directory
      suffix:       join
    register:       join_tmp_dir
    changed_when:   false
    
  - name: Copy the join command
    copy: 
      src:          "files/generated/k8s-cluster-attach-self.sh"
      dest:         "{{ join_tmp_dir.path }}"
      mode:         0700
    changed_when:   false
    
  - name: attach the node to cluster
    shell:          "sh {{ join_tmp_dir.path }}/k8s-cluster-attach-self.sh"
    become:         true
    
  always:
  - name: delete temporary build directory
    file:
      path:         "{{ join_tmp_dir.path }}"
      state:        absent
    when:           join_tmp_dir is defined
    changed_when:   false
  