---
- name: Copy the label node command to server location
  copy: 
    src:  files/local-label-node-k8s-cluster.sh
    dest: /tmp/label-node-k8s-cluster.sh
    mode: 0700
  become: true
  
- name: set workers type
  command: sh /tmp/label-node-k8s-cluster.sh
  become: true
  
- name: Copy the label node command to server location
  file: 
    path: /tmp/label-node-k8s-cluster.sh
    state: absent
  become: true
  
- name: Install dashboard-ui
    shell: kubectl apply -f 'https://raw.githubusercontent.com/kubernetes/dashboard/v2.0.0-beta4/aio/deploy/recommended.yaml'
  become: true
  
- name: copy dashboard-ui patch file
  template:
    src:   kubernetes-dashboard-ext.j2
    dest:  /root/kubernetes-dashboard-ext.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  
- name: patch dashboard-ui service to be accessed from remote
    shell: kubectl apply -f '/root/kubernetes-dashboard-ext.yml'
  become: true
  
- name: delete dashboard-ui patch file
  file: 
    path: /root/kubernetes-dashboard-ext.yml
    state: absent
  become: true
  
- name: generate dashboard-ui admin token
    shell: kubectl -n kubernetes-dashboard describe secret $(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')
  register: admin_token
  
- name: Copy admin token to local file
  copy:
    content: "{{ admin_token.stdout_lines[0] }}" 
    dest: "admin-token.txt"
  delegate_to: localhost
  