---
- name: create rbd pool
  block:
  - name: delete previous resource if it exists
    shell:          "ceph osd pool delete   {{ ceph.rbd_pool.name }}    {{ ceph.rbd_pool.name }}    --yes-i-really-really-mean-it"
    
  - name: create pool
    shell:          "ceph osd pool create   {{ ceph.rbd_pool.name }}    {{ ceph.rbd_pool.pg_num  | default(ceph.osd_pool.default_pg_num) }} {{ ceph.rbd_pool.pgp_num | default(ceph.osd_pool.default_pgp_num) }} replicated"
    
  - name: init rbd pool
    shell:          "rbd      pool init                 {{ ceph.rbd_pool.name }}"
    
  become:           true
  become_user:      ceph
  
- name: create pool user keyring
  block:
  - name: delete pool keyring
    file:
      path:         "/etc/ceph/ceph.client.{{ ceph.rbd_pool.name }}.keyring"
      state:        absent
    
  - name: create new keysring for pool
    shell:          "ceph auth get-or-create client.{{ ceph.rbd_pool.user }} mon 'profile rbd' osd 'profile rbd pool={{ ceph.rbd_pool.name }}'  mgr 'profile rbd pool={{ ceph.rbd_pool.name }}' -o /etc/ceph/ceph.client.{{ ceph.rbd_pool.name }}.keyring"
  become:           true
  become_user:      ceph
  
- name: retrieve ceph mon data
  shell:            "ceph mon dump --format json"
  register:         dump_command
  become:           true
  
- name: Copy ceph mon data to local file
  copy:
    content:        "{{ dump_command.stdout }}" 
    dest:           "files/generated/ceph_mon_dump.json"
  delegate_to:      localhost
  
- name: get rbd client key
  shell:            "ceph auth print-key client.{{ ceph.rbd_pool.user }}"
  register:         ceph_rbd_client_key_command
  changed_when:     false
  become:           true
  
- name: Copy ceph rbd client key data to local file
  copy:
    content:        "{{ ceph_rbd_client_key_command.stdout }}" 
    dest:           "files/generated/ceph_rbd_client.key"
  delegate_to:      localhost
  