---
- hosts: 
  - "{{ node_name }}"
  become: true
  tasks:
  - name: Set default value for plugin
    set_fact:  
      plugin: "calico"
    when: plugin|length < 1
  
  - name: set pod-network-cidr arg
    set_fact:
      pod_network_cidr_arg: "{% if plugin=='calico' %}--pod-network-cidr=\"192.168.0.0/16\"{% elif plugin=='flannel'%}--pod-network-cidr=\"10.244.0.0/16\"{% endif %}"
  
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ node_ip }}" --node-name "{{ node_name }}" --token="{{ k8s_token }}" {{ pod_network_cidr_arg }}
  
  - name: Setup kubeconfig for vagrant user
    command: "{{ item }}"
    with_items:
     - mkdir -p /home/vagrant/.kube
     - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
     - chown vagrant:vagrant /home/vagrant/.kube/config
  
  - name: Install calico pod network
    command: kubectl create -f "https://docs.projectcalico.org/v3.9/manifests/calico.yaml"
    become: false
    when:    plugin == "calico"
  
  - name: Install flannel pod network
    command: kubectl create -f "https://raw.githubusercontent.com/coreos/flannel/2140ac876ef134e0ed5af15c65e414cf26827915/Documentation/kube-flannel.yml"
    become: false
    when:    plugin == "flannel"
  
  - name: Install weave pod network
    command: kubectl create -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')&env.WEAVE_MTU=8912"
    become: false
    when:    plugin == "weave"
  