---
- hosts: 
  - "{{ node_name }}"
  become: true
  tasks:
  - name: add node to the cluster
    shell: kubeadm join --token "{{ k8s_token }}" {{ master_ip }}:6443 --discovery-token-unsafe-skip-ca-verification
  
