---
- name: Update and upgrade apt packages
  apt:
    upgrade: dist
    update_cache: yes
    autoremove:   yes
    force_apt_get: yes
  become: true
  
- name: add useful tooling
  apt:
    name: "{{ useful_tools }}"
    force_apt_get: yes
  become: true
  
- name: unarchive firmware files
  unarchive:
    src: "{{ firmware.archive }}"
    dest: /tmp
    mode: '0500'
    exclude: "{{ firmware.old_bin }}"
  changed_when: false
  become: true
  
- name: Check firmware version
  shell: "/tmp/vl805 -v /tmp/{{ firmware.new_bin }}"
  register: firmware_check
  changed_when: false
  become: true
  
- name: Update firmware if needed
  shell: "/tmp/vl805 -w /tmp/{{ firmware.new_bin }}"
  when: firmware_check.rc != 0
  become: true
  
- name: remove firmware files
  file: 
    path: "{{ item }}"
    state: absent
  with_items:
  - vl805
  - "{{ firmware.new_bin }}"
  changed_when: false
  become: true
  
- name: Set timezone
  timezone:
    name: "{{ timezone }}"
  become: true
  
# reboot if needed
- name: reboot on change
  reboot:
  when: firmware_check.rc != 0
  become: true
