- name: Wait for the end of the first boot apt
  shell: |
    timeout=$(($(date +%s) + 600))
    while pgrep 'apt' > /dev/null; do
        time=$(date +%s)
        if [[ $time -ge $timeout ]]; then
            exit 1
        fi
        sleep 1
    done
    exit 0
  changed_when: false
  