---
- name: clean ceph mon
  hosts: ceph_mon
  roles:
  - deploy-ceph-cluster/clean-ceph-mon
- name: clean ceph osd
  hosts: ceph_osd
  roles:
  - deploy-ceph-cluster/clean-ceph-osd
  
- name: 
  hosts:    ceph_master
  roles:
  - deploy-ceph-cluster/generate-ceph-conf
  
- name:     create ceph mon
  hosts:    ceph_mon
  roles:
  - deploy-ceph-cluster/create-ceph-mon
- name: create ceph osd
  hosts: ceph_osd
  roles:
  - deploy-ceph-cluster/create-ceph-osd
  