---
- name: Generate local private key (2048 bits, RSA)
  openssl_privatekey:
    path: "files/{{ domain_name }}.key"
    type: RSA
    size: 2048
  delegate_to: localhost
  
- name: Generate local csr
  openssl_csr:
    path: "files/{{ domain_name }}.csr"
    privatekey_path: files/ca.key
    common_name: "{{ certificate_authority.CN }}"
    state_or_province_name: "{{ certificate_authority.ST }}"
    organization_name: "{{ certificate_authority.O }}"
    organizational_unit_name: "{{ certificate_authority.OU }}"
    useCommonNameForSAN: false
    basicConstraints:
    - CA:TRUE
  delegate_to: localhost
  
- name: Generate local Self Signed Certificate Authority
  openssl_certificate:
    path: "files/{{ domain_name }}.crt"
    csr_path: files/ca.csr
    privatekey_path: files/ca.key
    provider: selfsigned
    selfsigned_digest: sha256
  delegate_to: localhost
  
- name: Ensures /etc/docker dir exists
  file: 
    path:  /etc/kubernetes/pki
    state: directory
    owner: root
    group: root
    mode:  '0755'
  become: true
  
- name: Copy key to /etc/kubernetes/pki
  copy: 
    src:  "files/{{ domain_name }}.key"
    dest: /etc/kubernetes/pki/ca.key
    owner: root
    group: root
    mode: '0400'
  become: true
  
- name: Copy certificate to /etc/kubernetes/pki
  copy: 
    src:  "files/{{ domain_name }}.crt"
    dest: /etc/kubernetes/pki/ca.crt
    owner: root
    group: root
    mode: '0444'
  become: true
  
# from here the role is not idempotent
- name: Reset the Kubernetes cluster using kubeadm
  command: kubeadm reset -f
  become: true
  
- block: kubernetes with flannel network plugin installation
    
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --node-name "{{ hostname }}" --cert-dir /etc/kubernetes/pki --pod-network-cidr="10.244.0.0/16"
    become: true
    
  - name: Install flannel pod network
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml" --kubeconfig /etc/kubernetes/admin.conf
    become: true
    
when: k8s.plugin == 'flannel'

- block: kubernetes with weave network plugin installation
    
  - name: get kubectl version
    shell:  kubectl version | base64 | tr -d '\n'
    register: kubectl_version
    become:  true
    changed_when: False
    
  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="{{ ansible_default_ipv4.address }}" --node-name "{{ hostname }}" --hostname-override "{{ fqdn }}" --cert-dir /etc/kubernetes/pki
    become: true
    
  - name: Install weave pod network
    command: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version={{ kubectl_version.stdout }}&env.WEAVE_MTU=8912" --kubeconfig /etc/kubernetes/admin.conf
    become: true
    
when: k8s.plugin == 'weave'

- name: Ensures .kube dir exists for root
  file: 
    path:  /root/.kube
    state: directory
    owner: root
    group: root
    mode:  '0700'
  become: true
  
- name: copy kube config to root
  copy:
    src:  /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode:  '0400'
    remote_src: yes
  become: true
  
- name: Ensures .kube dir exists for users
  file: 
    path:  "/home/{{ item }}/.kube"
    state: directory
    owner: "{{ item }}"
    group: "{{ item }}"
    mode:  '0700'
  with_items: "{{ work_users }}"
  become: true
  
- name: copy kube config to users
  copy:
    src:   /etc/kubernetes/admin.conf
    dest:  "/home/{{ item }}/.kube/config"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode:  '0400'
    remote_src: yes
  with_items: "{{ k8s.users }}"
  become: true
  
- name: Generate join command
  command:  kubeadm token create --print-join-command
  register: join_command
  become: true
  
- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
  