---
# disable IPV6
- name: ensure /boot/cmdline.txt exist
  copy:
    content: ""
    dest:  /boot/cmdline.txt
    force: no
    owner: root
    group: root
    mode:  '0644'
  become: true
  
- name: check cmdline ipv6.disable=1
  shell: (tr -s '[:space:]+ ' '\n' < /boot/cmdline.txt ) | grep -qq '^ipv6.disable=1$'
  register: cmdline_ipv6_disable
  failed_when:  false
  changed_when: false
  
- name: add   cmdline ipv6.disable_1 if needed
  shell: "{{ item }}"
  args:
    warn: false
  when: cmdline_ipv6_disable.rc != 0
  with_items:
  - cp -pf /boot/cmdline.txt /tmp/cmdline.txt
  - (tr -s '[:space:]+ ' '\n' < /tmp/cmdline.txt | sed '/^ipv6.disable=.*$/d;' ; printf "\nipv6.disable=1\n" ) | tr -s '\n' ' ' | sed 's/^\s*//; s/\s*$//' > /boot/cmdline.txt
  - rm -f /tmp/cmdline.txt
  become: true
  
- name: comment ipv6 hosts lines
  replace: 
    path:   /etc/hosts
    regexp: '^((?!#).*::[0-9].*)$'
    replace: '#\1'
  become: true
  
# set hostname and FQDN
- name: set hostname
  hostname:
    name: "{{ hostname }}"
  become: true
  
- name: remove raspberry from hosts
  lineinfile:
    path: /etc/hosts
    state: absent
    regexp: raspberrypi
  become: true
  
- name: add hotname and fqdn to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      127.0.1.1       {{ fqdn }} {{ hostname }}
      {{ ansible_eth0.ipv4.address }}    {{ fqdn }} {{ hostname }}
  become: true
  
# set static IP
- name: set static IP
  blockinfile:
    path: /etc/dhcpcd.conf
    block: |
      interface eth0
      static    ip_address={{ ansible_eth0.ipv4.address }}
      static    routers={{ gateway }}
      static    domain_name_servers={{ domain_name_servers }}
  register: dhcpcd_static_ip
  become: true
  
- name: check  cmdline ip
  shell: (tr -s '[:space:]+ ' '\n' < /boot/cmdline.txt ) | grep -qq '^ip=.*$'
  register: cmdline_ip
  failed_when:  false
  changed_when: false
  
- name: remove cmdline ip if needed
  shell: "{{ item }}"
  args:
    warn: false
  when: cmdline_ip.rc == 0
  with_items:
  - cp -pf /boot/cmdline.txt /tmp/cmdline.txt
  - (tr -s '[:space:]+ ' '\n' < /tmp/cmdline.txt | sed '/^ip\=.*$/d;') | tr -s '\n' ' ' | sed 's/^\s*//; s/\s*$//' > /boot/cmdline.txt
  - rm -f /tmp/cmdline.txt
  become: true
  
# disable wifi and bluetooth
- name: stop and disable services
  systemd:
    name: cron
    state: stopped
    enabled: false
  with_items:
  - hciuart
  - wpa_supplicant
  - bluetooth
  become: true
  
- name: ensure /boot/config.txt exist
  copy:
    content: "[all]"
    dest:  /boot/config.txt
    force: no
    owner: root
    group: root
    mode:  '0644'
  become: true
  
- name: add module bt and wifi toe disable list
  blockinfile:
    path: /boot/config.txt
    insertafter: "[all]"
    block: |
      dtoverlay=disable-wifi
      dtoverlay=disable-bt
  register: config_wifi_bt
  become: true
  
# reboot if needed
- name: reboot on change
  reboot:
  when: cmdline_ipv6_disable.rc != 0 or cmdline_ip.rc == 0 or dhcpcd_static_ip.changed or config_wifi_bt.changed
  become: true
  
