---
- name: Generate docker registry file on local
  template:
    src:            "k8s-docker-registry.j2"
    dest:           "files/generated/k8s-docker-registry.yml"
  delegate_to:      localhost
  
- name: copy docker registry file 
  copy:
    src:            "files/generated/k8s-docker-registry.yml"
    dest:           "/root/k8s/k8s-docker-registry.yml"
    owner:          root
    group:          root
    mode:           '0644'
  become:           true
  
- name: apply docker registry file 
  shell:            "kubectl apply -f '/root/k8s/k8s-docker-registry.yml'"
  become:           true
  