---
# not working for ubuntu 20.04
#- name: populate service facts
#  service_facts:
  
- name: get list of services
  shell:                "systemctl list-unit-files --no-page --type=service | grep ceph"
  register:             services_cmd
  changed_when:         false
  no_log:               true
  
- name: create services list
  set_fact:
    services_list:      "{{ ( services_cmd.stdout_lines | map('regex_replace', '^(.*\\.service) .*$', '\\1') | list ) }}"
  
- name: create services dict
  set_fact:
    services:           "{{ dict( services_list | zip( services_list )) }}"
  
- name: execute ceph volume data command
  shell:                "ceph-volume lvm list --format json"
  register:             ceph_volumes_command
  changed_when:         false
  failed_when:          false
  become:               true
  
- name: create ceph_volumes dict
  set_fact:
    ceph_volumes:       "{{ (ceph_volumes_command.stdout | from_json).values() | flatten | map(attribute='tags') | flatten | list }}"
  when:                 ceph_volumes_command.rc == 0
  
- name: stop and disable osd services if exist
  systemd:
    name:               "ceph-osd@{{ item['ceph.osd_id'] }}.service"
    state:              stopped
    enabled:            false
  with_items:       "{{ ceph_volumes }}"
  when:
  - "'ceph-osd@.service'    in services.keys()"
  - ceph_volumes is defined
  become:           true
  
- name: ensure ceph base binaries is installed
  apt: 
    name:           "{{ packages }}"
    state:          present
    update_cache:   yes
    autoremove:     yes
    force_apt_get:  yes
  vars:
    packages:
    - "ceph-base"
    - "ceph-common"
    - "lvm2"
  become:           true
  
## remove ceph packages
- name: remove ceph osd packages and their dependencies
  apt: 
    name:           "{{ packages }}"
    state:          absent
    force_apt_get:  yes
    purge:          yes
  vars:
    packages:
    - "ceph-osd"
  become:           true
  
- name: Unmount ceph osd folders
  mount:
    path:           "{{ item }}"
    state:          unmounted
  with_items:       "{{ ansible_mounts | map(attribute='mount') | select( 'match', '^/var/lib/ceph/osd/.*' ) | list }}"
  become:           true
  
- name: retrieve all vgs
  shell:            "vgs --noheadings --options vg_name"
  register:         vgs_command
  changed_when:     false
  become:           true
  
- name: Remove ceph volume group
  lvg:
    vg:             "{{ item }}"
    state:          absent
    force:          yes
  with_items:       "{{ vgs_command.stdout_lines |  map('trim') | select( 'match', '^ceph-.*' ) | list }}"
  become:           true
  
- name: find all ceph files
  find:
    paths:          "{{ item }}"
    file_type:      file
  with_items:
  - "/run/ceph"
  - "/var/lib/ceph"
  - "/etc/ceph"
  register:         ceph_files
  become:           true
  
- name: delete all ceph files
  file:
    path:           "{{ item.path }}"
    state:          absent
  with_items:       "{{ ceph_files.results | map(attribute='files') | list | flatten }}"
  become:           true
  