---
apiVersion: v1
kind:           Namespace
metadata:
  name:         rbd-csi
---
apiVersion:     v1
kind:           ServiceAccount
metadata:
  name:         rbd-csi-nodeplugin
  namespace:    rbd-csi
---
apiVersion:     v1
kind:           ServiceAccount
metadata:
  name:         rbd-csi-provisioner
  namespace:    rbd-csi
---
kind:           ClusterRole
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-external-provisioner-runner
  namespace:    rbd-csi
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.rbd.csi.ceph.com/aggregate-to-rbd-external-provisioner-runner: "true"
rules:          []
---
kind:           ClusterRole
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-external-provisioner-runner-rules
  namespace:    rbd-csi
  labels:
    rbac.rbd.csi.ceph.com/aggregate-to-rbd-external-provisioner-runner:     "true"
rules:
  - apiGroups:  [""]
    resources:  ["nodes"]
    verbs:      ["get", "list", "watch"]
  - apiGroups:  [""]
    resources:  ["secrets"]
    verbs:      ["get", "list"]
  - apiGroups:  [""]
    resources:  ["events"]
    verbs:      ["list", "watch", "create", "update", "patch"]
  - apiGroups:  [""]
    resources:  ["persistentvolumes"]
    verbs:      ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups:  [""]
    resources:  ["persistentvolumeclaims"]
    verbs:      ["get", "list", "watch", "update"]
  - apiGroups:  ["storage.k8s.io"]
    resources:  ["storageclasses"]
    verbs:      ["get", "list", "watch"]
  - apiGroups:  ["snapshot.storage.k8s.io"]
    resources:  ["volumesnapshots"]
    verbs:      ["get", "list", "watch", "update"]
  - apiGroups:  ["snapshot.storage.k8s.io"]
    resources:  ["volumesnapshotcontents"]
    verbs:      ["create", "get", "list", "watch", "update", "delete"]
  - apiGroups:  ["snapshot.storage.k8s.io"]
    resources:  ["volumesnapshotclasses"]
    verbs:      ["get", "list", "watch"]
  - apiGroups:  ["apiextensions.k8s.io"]
    resources:  ["customresourcedefinitions"]
    verbs:      ["create", "list", "watch", "delete", "get", "update"]
  - apiGroups:  ["storage.k8s.io"]
    resources:  ["volumeattachments"]
    verbs:      ["get", "list", "watch", "update", "patch"]
  - apiGroups:  ["storage.k8s.io"]
    resources:  ["csinodes"]
    verbs:      ["get", "list", "watch"]
  - apiGroups:  ["snapshot.storage.k8s.io"]
    resources:  ["volumesnapshots/status"]
    verbs:      ["update"]
  - apiGroups:  [""]
    resources:  ["persistentvolumeclaims/status"]
    verbs:      ["update", "patch"]
---
kind:           ClusterRole
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-csi-nodeplugin-rules
  namespace:    rbd-csi
  labels:
    rbac.rbd.csi.ceph.com/aggregate-to-rbd-csi-nodeplugin: "true"
rules:
  - apiGroups:  [""]
    resources:  ["nodes"]
    verbs:      ["get"]
---
kind:           ClusterRoleBinding
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-csi-provisioner-role
  namespace:    rbd-csi
subjects:
  - kind:       ServiceAccount
    name:       rbd-csi-provisioner
    namespace:  rbd-csi
roleRef:
  kind:         ClusterRole
  name:         rbd-external-provisioner-runner
  apiGroup:     rbac.authorization.k8s.io
---
kind:           ClusterRoleBinding
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-csi-nodeplugin
  namespace:    rbd-csi
subjects:
  - kind:       ServiceAccount
    name:       rbd-csi-nodeplugin
    namespace:  rbd-csi
roleRef:
  kind:         ClusterRole
  name:         rbd-csi-nodeplugin
  apiGroup:     rbac.authorization.k8s.io
---
kind:           ClusterRole
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-csi-nodeplugin
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.rbd.csi.ceph.com/aggregate-to-rbd-csi-nodeplugin: "true"
rules:          []
---
kind:           Role
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-external-provisioner-cfg
  namespace:    rbd-csi
rules:
  - apiGroups:  [""]
    resources:  ["configmaps"]
    verbs:      ["get", "list", "watch", "create", "delete"]
  - apiGroups:  ["coordination.k8s.io"]
    resources:  ["leases"]
    verbs:      ["get", "watch", "list", "delete", "update", "create"]
---
kind:           RoleBinding
apiVersion:     rbac.authorization.k8s.io/v1
metadata:
  name:         rbd-csi-provisioner-role-cfg
  namespace:    rbd-csi
subjects:
  - kind:       ServiceAccount
    name:       rbd-csi-provisioner
    namespace:  rbd-csi
roleRef:
  kind:         Role
  name:         rbd-external-provisioner-cfg
  apiGroup:     rbac.authorization.k8s.io
---